apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: jev67m3og-nodejs 
  janus-idp.io/tekton: jev67m3og-nodejs
  backstage.io/kubernetes-id: jev67m3og-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jev67m3og-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  