apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: jev67m3og-nodejs-gitops
  description: This is GitOps manifest for jev67m3og-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: jev67m3og-nodejs
    janus-idp.io/tekton: jev67m3og-nodejs 
    backstage.io/kubernetes-id: jev67m3og-nodejs 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:jev67m3og-nodejs
