apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: jev67m3og-nodejs
  janus-idp.io/tekton: jev67m3og-nodejs
  backstage.io/kubernetes-id: jev67m3og-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jev67m3og-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
